import Entity from '../entity';
import {
  NESTLE_OUR_BRANDS,
  NESTLE_SOAKED_WATER_CONTROVERSY,
} from './constants';
import { Child } from './types';

/*
To add a child company, use the format
  ChildCompanyName: {
    parent: Entity.ParentCompany,
    source: 'https://...',
  },
*/
const CHILDREN: Record<string, Child> = {
  Aero: NESTLE_OUR_BRANDS,
  Alpo: NESTLE_OUR_BRANDS,
  'Baby Ruth': NESTLE_SOAKED_WATER_CONTROVERSY,
  'Bakers Complete': NESTLE_OUR_BRANDS,
  Beneful: NESTLE_OUR_BRANDS,
  'Blue Bottle Coffee Company': {
    parent: Entity.Nestle,
    sources: [
      'https://www.nytimes.com/2017/09/14/business/dealbook/nestle-blue-bottle-coffee.html',
    ],
  },
  Bonka: {
    parent: Entity.Nestle,
    sources: ['https://books.google.com/books?id=O2hVVxHY9ecC&pg=PA176'],
  },
  Boost: NESTLE_OUR_BRANDS,
  Buitoni: NESTLE_OUR_BRANDS,
  Butterfinger: NESTLE_SOAKED_WATER_CONTROVERSY,
  Cailler: NESTLE_OUR_BRANDS,
  Carnation: NESTLE_OUR_BRANDS,
  'Cat Chow': NESTLE_OUR_BRANDS,
  Cerelac: NESTLE_OUR_BRANDS,
  Cheerios: NESTLE_OUR_BRANDS,
  Chef: NESTLE_OUR_BRANDS,
  'Chef-Mate': NESTLE_OUR_BRANDS,
  "Chef Michael's Canine Creations": NESTLE_OUR_BRANDS,
  'Chips Ahoy!': NESTLE_SOAKED_WATER_CONTROVERSY,
  'Coffee-Mate': NESTLE_OUR_BRANDS,
  'Dog Chow': NESTLE_OUR_BRANDS,
  "Dreyer's": NESTLE_OUR_BRANDS,
  Extreme: NESTLE_OUR_BRANDS,
  'Fancy Feast': NESTLE_OUR_BRANDS,
  Felix: NESTLE_OUR_BRANDS,
  Fitness: NESTLE_OUR_BRANDS,
  Friskies: NESTLE_OUR_BRANDS,
  Gerber: NESTLE_OUR_BRANDS,
  'Golden Grahams': NESTLE_SOAKED_WATER_CONTROVERSY,
  Gourmet: NESTLE_OUR_BRANDS,
  'Juicy Juice': NESTLE_SOAKED_WATER_CONTROVERSY,
  'Haagen-Dazs': NESTLE_OUR_BRANDS,
  Herta: NESTLE_OUR_BRANDS,
  'Hot Pockets': NESTLE_OUR_BRANDS,
  KitKat: NESTLE_OUR_BRANDS,
  'La Laitiere': NESTLE_OUR_BRANDS,
  'Lean Cuisine': NESTLE_OUR_BRANDS,
  "Libby's": NESTLE_SOAKED_WATER_CONTROVERSY,
  Lion: NESTLE_OUR_BRANDS,
  Maggi: NESTLE_OUR_BRANDS,
  Milkybar: NESTLE_OUR_BRANDS,
  Milo: NESTLE_OUR_BRANDS,
  "Minor's": NESTLE_OUR_BRANDS,
  Movenpick: NESTLE_OUR_BRANDS,
  NaturNes: NESTLE_OUR_BRANDS,
  Nescafe: NESTLE_OUR_BRANDS,
  'Nescafe 3 in 1': NESTLE_OUR_BRANDS,
  'Nescafe Cappuccino': NESTLE_OUR_BRANDS,
  'Nescafe Classic': NESTLE_OUR_BRANDS,
  'Nescafe Decaff': NESTLE_OUR_BRANDS,
  'Nescafe Dolce Gusto': NESTLE_OUR_BRANDS,
  'Nescafe Gold': NESTLE_OUR_BRANDS,
  Nespresso: NESTLE_OUR_BRANDS,
  Nesquik: NESTLE_OUR_BRANDS,
  'Nesquik Cereal': NESTLE_OUR_BRANDS,
  Nestea: NESTLE_OUR_BRANDS,
  'Nestle Ice Cream': NESTLE_OUR_BRANDS,
  'Nestle Pure Life': NESTLE_OUR_BRANDS,
  "Nestle Les Recettes de l'Atelier": NESTLE_OUR_BRANDS,
  Nido: NESTLE_OUR_BRANDS,
  'Nutren Junior': NESTLE_OUR_BRANDS,
  Oreo: NESTLE_SOAKED_WATER_CONTROVERSY,
  Orion: NESTLE_OUR_BRANDS,
  Peptamen: NESTLE_OUR_BRANDS,
  Perrier: NESTLE_OUR_BRANDS,
  'Poland Spring': NESTLE_OUR_BRANDS,
  PowerBar: NESTLE_SOAKED_WATER_CONTROVERSY,
  Purina: NESTLE_OUR_BRANDS,
  'Purina ONE': NESTLE_OUR_BRANDS,
  'Purina Pro Plan': NESTLE_OUR_BRANDS,
  'Quality Street': NESTLE_OUR_BRANDS,
  Resource: NESTLE_OUR_BRANDS,
  'S. Pellegrino': NESTLE_OUR_BRANDS,
  'Shredded Wheat': NESTLE_SOAKED_WATER_CONTROVERSY,
  Sjora: NESTLE_OUR_BRANDS,
  Smarties: NESTLE_OUR_BRANDS,
  'Special.T': {
    parent: Entity.Nestle,
    sources: [
      'http://uk.reuters.com/article/uk-nestle-specialt-idUKBRE96U05C20130731',
      'https://www.designweek.co.uk/inspiration/nestle-special-t-packaging-bb-studio/',
      'https://www.nytimes.com/2010/05/20/business/global/20tea.html',
    ],
  },
  "Stouffer's": NESTLE_OUR_BRANDS,
  Supligen: {
    parent: Entity.Nestle,
    sources: [
      'https://www.dairyreporter.com/Article/2015/11/19/Nestle-Jamaica-to-divest-local-dairy-business-to-focus-on-international-brands',
    ],
  },
  "Taster's Choice": NESTLE_SOAKED_WATER_CONTROVERSY,
  Thomy: NESTLE_OUR_BRANDS,
  'Toll House': NESTLE_OUR_BRANDS,
  Wonka: NESTLE_SOAKED_WATER_CONTROVERSY,
};

export default CHILDREN;
